/* **** The fundamental basic-skeleton is generated by QGIS **** */
/* **** Leaflet **** */

// Overlay layers (TMS)
var lyr = L.tileLayer('./{z}/{x}/{y}.png', {tms: true, opacity: 1, attribution: 'Generated by &copy; <a href="https://www.cottbus.de/verwaltung/gb_iv/stadtentwicklung/">Stadtentwicklung Cottbus, </a>Oktober 2021, <a href="https://stadtentwicklung.github.io/masterplan/">UPDATE</a>', minZoom: 10, maxZoom: 15});

// Map
var map = L.map('map', {
    center: [51.78179619043856, 14.430890490667228],
    //zoom: 15,
    minZoom: 10,
    maxZoom: 15,
    layers: lyr,
	loadingControl: true
});

// Title
var title = L.control();
title.onAdd = function(map) {
    this._div = L.DomUtil.create('div', 'ctl title');
    this.update();
    return this._div;
};

title.update = function(props) {
    this._div.innerHTML = "Masterplan Cottbuser Ostsee 3.0";
};

title.addTo(map);

// Fit to overlay bounds (SW and NE points with (lat, lon))
map.fitBounds([[51.72837123461897, 14.552784241190125], [51.83522114625816, 14.30899674014433]]);
		
// Geolocating		
function onLocationFound(e) {
    var location = e.latlng
    L.marker(location).addTo(map).bindPopup("Du bist ungef&auml;hr hier.").openPopup();
};

function onLocationError(e) {
	alert(e.message);
};

function getLocationLeaflet() {
	map.on('locationfound', onLocationFound);
	map.on('locationerror', onLocationError);
	map.locate({setView: true, maxZoom: 15});
};
		
// Custom project-marker
var redIcon = new L.Icon({
	iconUrl: 'https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-2x-red.png',
	shadowUrl: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/images/marker-shadow.png',
	iconSize: [25, 41],
	iconAnchor: [12, 41],
	popupAnchor: [1, -34],
	shadowSize: [41, 41]
});

//1
L.marker([51.77727, 14.39582], {icon: redIcon}).addTo(map).bindPopup("<b>1 Hafenquartier Cottbus &vert; P&sacute;istawowy kwart&ecaron;r Ch&oacute;&sacute;ebuz</b><br>Mit dem Hafenquartier wird Cottbus&sol;Ch&oacute;&sacute;ebuz eine &bdquo;Stadt am Wasser&ldquo;. Am Endpunkt der Seeachse entsteht zwischen dem Ufer des Cottbuser Ostsees und der B168 ein neues innovatives und vielf&auml;ltiges Quartier mit Promenade, Stadthafen und etwa 200 Bootsliegepl&auml;tzen. Neben einem breit gef&auml;cherten Wassersportbereich, einem Sport&ndash; und Gesundheitszentrum, Wohnungen, Gesch&auml;ften, Restaurants sowie einem Hotel- und Veranstaltungskomplex entsteht das &bdquo;Forum Lausitz&sol;Carboneum&ldquo; &ndash; ein Infozentrum zur wechselvollen Beziehung zwischen der Kulturgeschichte, dem Naturraum und der Kohlef&ouml;rderung in der Region. Das Hafenquartier soll als erstes Quartier in Cottbus&sol;Ch&oacute;&sacute;ebuz dem Anspruch einer CO<sub>2</sub>&ndash;neutralen Stadtentwicklung gerecht werden. Beginnend bei der Planung, Materialwahl und Konstruktion &uuml;ber eine innovative Mobilit&auml;tskonzeption bis hin zur CO<sub>2</sub>&ndash;neutralen Energieversorgung soll das Hafenquartier bundesweit Ma&#223;st&auml;be f&uuml;r eine nachhaltige und klimagerechte urbane Entwicklung setzen.");
//2
L.marker([51.77004, 14.37917], {icon: redIcon}).addTo(map).bindPopup("<b>2 Seevorstadt &vert; Jazorowe p&sacute;edm&ecaron;sto</b><br>Die st&auml;dtebauliche Verbindung zwischen Innenstadt und Cottbuser Ostsee ist eines der wichtigsten Projekte in den n&auml;chsten Jahrzehnten und Initial einer CO<sub>2</sub>&ndash;neutralen und klimaresilienten Entwicklung von Cottbus&sol;Ch&oacute;&sacute;ebuz. Kern dieser Verbindung ist die ehemalige Bahntrasse Cottbus &ndash;Guben, die im Jahr 2000 durch den Tagebau obsolet wurde. Hier soll ein urbaner gr&uuml;ner Freiraum f&uuml;r Fu&#223;g&auml;nger, Radfahrer und den &Ouml;PNV entstehen. Die stadtr&auml;umliche Ausrichtung hin zum Wasser wird dabei durch die Entwicklung der Seevorstadt entlang dieser Verbindungsachse flankiert. Hier entsteht ein Zukunftsraum in Form eines modernen, urbanen und nachhaltigen Stadtquartiers und gro&#223;z&uuml;gigen Gr&uuml;nr&auml;umen. Die Planungen sehen neue Wohnbereiche, attraktive Gewerbefl&auml;chen, einen innovativen Energiecampus als Denkfabrik sowie ein Bildungs- und Beh&ouml;rdenzentrum mit zahlreichen Arbeitspl&auml;tzen vor. Neue Funktionen und Gestaltungsqualit&auml;ten im Sinne eines grundlegenden Stadtumbauprozesses sowie innovativer &ouml;ffentlicher Nahverkehr definieren die Anspr&uuml;che an die zuk&uuml;nftige Stadtentwicklung im Cottbuser Osten.");
//3
L.marker([51.78746, 14.38042], {icon: redIcon}).addTo(map).bindPopup("<b>3 Merzdorf &vert; &Zcaron;ylowk</b><br>Nordwestlich, in unmittelbarer Nachbarschaft zum Hafenquartier entstehen Wohnbebauungen als Erg&auml;nzung zum Siedlungsgebiet von Merzdorf mit dem Vorzug der N&auml;he zur Stadt und zum Wasser. Hier sollen Wohnungen in moderner Architektursprache und dem Anspruch an eine CO<sub>2</sub>&ndash;neutrale Stadtentwicklung entstehen. Flankiert wird das Quartier durch den Merzdorfer Strand, der vor allem f&uuml;r Cottbuser Badeg&auml;ste mit dem Fahrrad und zu Fu&#223; gut erreichbar ist.");
//4
L.marker([51.7975, 14.38316], {icon: redIcon}).addTo(map).bindPopup("<b>4 Lakoma &ndash; Willmersdorf &vert; &Lstrok;akoma &ndash; Rogozno</b><br>Die ehemalige Dorflage Lakoma bildet den zentralen Knotenpunkt am See f&uuml;r Radfahrer zwischen See-Rundweg und (&uuml;ber-)regionalen Radwanderwegen bzw. umgekehrt. Vor dem Westufer des Cottbuser Ostsees soll eine schwimmende Insel mit Gastst&auml;tte und Ferienwohnungen entstehen. Der naturbelassene Uferabschnitt mit Uferweg l&auml;dt zu Seespazierg&auml;ngen unmittelbar am Wasser ein. N&ouml;rdlich von Lakoma befindet sich der Willmersdorfer Strand, der ideal f&uuml;r Badeg&auml;ste aus dem lokalen Umfeld aber auch f&uuml;r Radtouristen entlang des Rundweges geeignet ist.");
//5
L.marker([51.80482, 14.42282], {icon: redIcon}).addTo(map).bindPopup("<b>5 Hafen Teichland &vert; P&sacute;istaw Gatojce</b><br>Am s&uuml;dlichen Rand des Ortsteils Neuendorf der Gemeinde Teichland entsteht ein &bdquo;Seehafen&ldquo;. Die Planung sieht die Errichtung eines Sportboothafens mit einer Wasserfl&auml;che von ca. 16.000m&sup2; f&uuml;r 100 Bootsliegepl&auml;tze vor. Um das k&uuml;nftige Hafenbecken wird ein Hafenquartier mit einer Seepromenade, die einen Ausblick &uuml;ber den Hafen und auf den Ostsee bietet, entstehen. Die Pormenade bindet im Osten an die &bdquo;Seeachse&ldquo; an und f&uuml;hrt weiter zur Anlegestelle f&uuml;r die Fahrgastschifffahrt und zum &bdquo;Erlebnispark&ldquo;. An der Promenade angelagert sind Fl&auml;chen f&uuml;r maritimes Gewerbe, Gastronomie und Beherbergungsst&auml;tten. Weiterhin sind im Hafenquartier Fl&auml;chen f&uuml;r Hafenbetrieb, Werkstatt, Bootslagerhalle sowie Ferienwohnungen und &ndash;h&auml;user geplant. Baufl&auml;chen f&uuml;r Wohnh&auml;user tragen zur ganzj&auml;hrigen Belebung des Quartiers bei.");
//6
L.marker([51.80745, 14.44994], {icon: redIcon}).addTo(map).bindPopup("<b>6 B&auml;renbr&uuml;cker H&ouml;he &vert; Barbucka wu&scaron;yna</b><br>Die B&auml;renbr&uuml;cker H&ouml;he ist eine k&uuml;nstliche Erhebung, die ca. 440 ha umfasst und etwa 30 m &uuml;ber dem nat&uuml;rlichen Umland liegt. Gemeinsam mit dem Erlebnispark &bdquo;Teichland&ldquo; und dem Aussichtsturm bildet sie das Zentrum der touristischen Angebote am n&ouml;rdlichen Seeufer. Im Erlebnispark befinden sich Themeng&auml;rten mit unterschiedlichen Schwerpunkten, wie z.B. die sportlichen Aktivit&auml;ten, der &bdquo;Slawische G&ouml;tterhain&ldquo; und den &bdquo;Pfad der kleinen G&ouml;tter&ldquo;. Der Aussichtsturm erm&ouml;glicht einen weiten Blick auf den zuk&uuml;nftigen See.");
//7
L.marker([51.79691, 14.44921], {icon: redIcon}).addTo(map).bindPopup("<b>7 B&auml;renbr&uuml;cker Bucht &vert; Barbucka wu&scaron;yna</b><br>Die B&auml;renbr&uuml;cker Bucht eignet sich ideal f&uuml;r l&auml;rmintensivere Veranstaltungen von Musik, &uuml;ber Schauspiel bis hin zu Gro&#223;&ndash; und Privatveranstaltungen. Zudem ist sie der Surf&ndash;Point am See. Die Wasserfl&auml;che und der Strand in der Bucht bieten mit ihrer S&uuml;dausrichtung beste Verh&auml;ltnisse f&uuml;r Kite Surfer. Saisonale Gastronomie, Surfschul&ndash; und Verleihangebote sowie eine Zeltwiese, ein Wohnmobilstellplatz und ein gro&#223;es Sportfeld sollen unter dem Anspruch des CO<sub>2</sub>&ndash;neutralen Bauens und des schonenden Umgangs mit Ressourcen als Planungspr&auml;misse, Raum f&uuml;r nachhaltigen aktiven Wassersporttourismus bieten.");
//8
L.marker([51.78252, 14.47835], {icon: redIcon}).addTo(map).bindPopup("<b>8 Energiezentrum &vert; Energijowy centrum</b><br>Auf den ehemaligen Tagesanlagen des Braunkohletagebaus entsteht ein Wirtschaftsstandort f&uuml;r Industrie und produzierendes Gewerbe mit Fokus auf Erneuerbare Energien und Kreislaufwirtschaft. Das verkehrlich gut erschlossene Gewerbegebiet der heutigen Tagesanlagen soll zu einem Technologie&ndash; und Gr&uuml;nderzentrum f&uuml;r Zukunftsenergien (Schwerpunkt nachwachsende Rohstoffe, alternative Energiegewinnung) auf einer Gesamtfl&auml;che von ca. 55 ha ausgebaut werden.");
//9
L.marker([51.78239, 14.4593], {icon: redIcon}).addTo(map).bindPopup("<b>9 Energielandschaft &vert; Energijowa krajina</b><br>&Ouml;stlich des Sees, zwischen Rundweg und Energiezentrum, wird eine gr&uuml;ne Energielandschaft vorgeschlagen. Schwerpunkt soll zuk&uuml;nftig die Erzeugung erneuerbarer Energien im Einklang mit der &uuml;berwiegend forstwirtschaftlich und naturnah gepr&auml;gten Nachnutzung der Bergbaufolgelandschaft sein. Anlagen zur Umwandlung von Wind- und Sonnenergie in Strom verk&ouml;rpern hier den Wandel der Energieversorgung. Besucher k&ouml;nnen sich an Infotafeln entlang des Rundweges &uuml;ber die Historie der Energiegewinnung informieren.");
//10
L.marker([51.75012, 14.48234], {icon: redIcon}).addTo(map).bindPopup("<b>10 Klinger See &vert; Klinca&nacute;ski jazor</b><br>Dem Klinger See wird mit der Schaffung und dem Erhalt von wertvollen Natur&ndash; und Landschaftsarealen sowie der Entwicklung eines naturnahen Tourismus besondere Bedeutung einger&auml;umt. Durch seine Ausformung ist er pr&auml;destiniert f&uuml;r eine professionelle Regattastrecke &uuml;ber 2.500 bis 3.000 m. Ein &bdquo;Rudersportzentrum&ldquo; fast das Wassersportangebot k&uuml;nftig sehr zentral zusammen und k&ouml;nnte von vielen Sportvereinen genutzt werden. Mit der Freigabe des Sees ist aufgrund des prognostizierten Abschlusses der Flutung deutlich nach der Fertigstellung des Cottbuser Ostsees zu rechnen.");
//11
L.marker([51.74994, 14.44685], {icon: redIcon}).addTo(map).bindPopup("<b>11 Naturstrand S&uuml;dspitze &vert; P&sacute;irodny p&oacute;dpo&lstrok;dnjowy p&sacute;ibrjog</b><br>Aufgrund seiner Erhebung ist dieses Areal die visuelle Schnittstelle zwischen dem Klinger See und dem Cottbuser Ostsee. Hier soll auf einer L&auml;nge von ca. 250 m der Naturstrand des Sees f&uuml;r Freunde der Freik&ouml;rperkultur und Badeg&auml;ste mit hohem Naturbed&uuml;rfnis angelegt werden. Eine intensive Freizeit&ndash; und Tourismusnutzung ist daher nicht vorgesehen. Der Strand ist zu Fu&#223; und mit dem Fahrrad entlang des Rundweges erreichbar.");
//12
L.marker([51.75482, 14.41677], {icon: redIcon}).addTo(map).bindPopup("<b>12 Entwicklungsraum Schlichow&ndash;S&uuml;d &vert; Wuwija&nacute;ski rum &Scaron;lichow&ndash;p&oacute;dpo&lstrok;dnjo</b><br>S&uuml;dlich der Ortslage Schlichow bildet eine k&uuml;nstlich geschaffene, bewegte Landschaft den Auftakt der Binnend&uuml;nenlandschaft entlang des S&uuml;d-Westufers. Hier sind gro&#223;fl&auml;chige Freizeit- und Sportnutzungen denkbar, welche mit dem l&auml;ndlichen Charakter des Umfeldes korrespondieren und gleichzeitig vor allem ruhebed&uuml;rftige sowie naturaffine Ausfl&uuml;gler und Anwohner begeistern.");
//13
L.marker([51.76131, 14.41381], {icon: redIcon}).addTo(map).bindPopup("<b>13 Schlichow &vert; &Scaron;lichow</b><br>Schlichow liegt direkt am zuk&uuml;nftigen Cottbuser Ostsee. Hier entstehen zus&auml;tzliche Wohnbaufl&auml;chen durch Arrondierung und Nachverdichtung. Mit der Gestaltung des Platzes am Anger als Scharnier zwischen Siedlung und Schiffsanleger am See entsteht eine neue Ortsmitte. Entlang des Platzes sind ein Mehrzweckgeb&auml;ude, ein Rast- und Servicepunkt f&uuml;r Radfahrer, eine E-Bike-Ladestation sowie eine Radler Herberge geplant. Der ehemalige L&auml;rmschutzdamm soll als identit&auml;tsstiftende Landmarke des &bdquo;Dorfes hinter den D&uuml;nen&ldquo; teilweise erhalten und umgestaltet werden.");
//14
L.marker([51.75772, 14.42844], {icon: redIcon}).addTo(map).bindPopup("<b>14 Schlichow S&uuml;d &vert; &Scaron;lichow P&oacute;dpo&lstrok;dnjowy</b><br>S&uuml;d&ouml;stlich von Schlichow soll aufgrund der Standortqualit&auml;ten ein kleines aber feines Urlauberzentrum f&uuml;r Sport und Wellness entstehen. Auch ein hoteleigener Strand und ein kleiner Steg sind denkbar. Der Strand ist f&uuml;r Fu&#223;g&auml;nger und Radfahrer erreichbar. Sportboote und Slipanlagen wird es hier jedoch nicht geben, da diese ausschlie&#223;lich in den beiden H&auml;fen am See vorgesehen sind.");
//15
L.marker([51.76935, 14.40325], {icon: redIcon}).addTo(map).bindPopup("<b>15 Cottbuser Strand &vert; Ch&oacute;&sacute;ebuski p&sacute;ibrjog</b><br>Zwischen dem Stadthafen und Schlichow entsteht mit ca. 18 ha der Hauptstrand des Sees mit regionaler Ausstrahlung. Neben dem Badestrand und Sportm&ouml;glichkeiten bieten Sitzgelegenheiten, Versorgungseinrichtungen, Umkleiden, Sanit&auml;ranlagen sowie der Verleih von Liegen, Sonnenschirmen und Booten eine hohe Aufenthaltsqualit&auml;t. Der Strand ist &uuml;ber den Rundweg zu Fu&#223;, mit Rad, mit Skates sowie &uuml;ber die B168 mit &Ouml;PNV und PKW gut zu erreichen. F&uuml;r die geplanten Nutzungen besteht ebenso wie f&uuml;r das benachbarte Hafenquartier der Anspruch an eine CO<sub>2</sub>&ndash;neutrale Bauweise und einen ressourcenschonenden Betrieb.");
//16
L.marker([51.74297, 14.36965], {icon: redIcon}).addTo(map).bindPopup("<b>16 Schlosspark Branitz &vert; Grodowy park Roge&nacute;c</b><br>Der Landschaftsraum um die Schlichower H&ouml;he soll landschaftsgestalterisch eine Verbindung mit der Branitzer Park&ndash; und Kulturlandschaft eingehen. Den Kern dieser Verbindung bildet die historische Kastanienallee, einst herrschaftliche Anfahrt zum Schloss und Park Branitz, als Fu&#223;&ndash; und Fahrradweg. Das Thema Landschaftsgestaltung soll als Attraktionsmerkmal f&uuml;r den Cottbuser Ostsee genutzt werden. Der Branitzer Park ist die historische Kulturlandschaft, der Cottbuser Ostsee ihre moderne Interpretation.");
//17
L.marker([51.76085, 14.462], {icon: redIcon}).addTo(map).bindPopup("<b>17 Rundweg &vert; Woko&lstrok;ny pu&sacute;</b><br>Um den Cottbuser Ostsee herum entsteht ein 27 km langer Rundweg, der Wanderern, Radfahrern, Skatern und Joggern vorbehalten ist. Der &bdquo;Ostsee&ndash;Rundweg&ldquo; wird in das Brandenburger Radverkehrsnetz sowie die bereits vorhandenen regionalen Radwanderwege eingebunden. Der Weg verbindet die einzelnen Standorte, Projekte, Str&auml;nde und Hotels am Cottbuser Ostsee. Die Bedeutung des Rundweges soll durch eine hochattraktive landschaftsplanerische Ausformung, sowohl in der M&ouml;blierung (z.B. Sitzb&auml;nke, Infotafeln bei Raststationen etc.) als auch in der Oberfl&auml;chengestaltung, erlebbar werden.");
//18
L.marker([51.7752, 14.44389], {icon: redIcon}).addTo(map).bindPopup("<b>18 Lieskower Bucht &vert; Li&scaron;kojski zalew</b><br>Das buchtenreiche Ostufer des Cottbuser Ostsees ist mit seinen vorgelagerten Inseln bzw. Halbinseln der naturbelassenen, gesch&uuml;tzten Entwicklung von Flora und Fauna vorbehalten. Die Entstehung einer Vogelinsel mit Beobachtungssteg soll an dieser Stelle bef&ouml;rdert werden.");
//19
L.marker([51.74677, 14.45994], {icon: redIcon}).addTo(map).bindPopup("<b>19 Seen&ndash;Radweg &vert; Jazorowy k&oacute;lasa&racute;ski pu&sacute;</b><br>Eine Verlegung des F&uuml;rst&ndash;P&uuml;ckler&ndash;Radweges soll den Cottbuser Ostsee mit dem Klinger See verbinden und auf diese Weise die neu entstehende Seenlandschaft f&uuml;r den aktiven, naturnahen und CO<sub>2</sub>&ndash;neutralen Rad&ndash; und Wandertourismus erlebbar machen. Hierf&uuml;r sind planfreie, unabh&auml;ngige Querungen der B97 und der Trasse der ehemaligen Grubenbahn angedacht.");
//20
L.marker([51.78125, 14.42406], {icon: redIcon}).addTo(map).bindPopup("<b>20 Seezeichen &vert; Jazorowy znamje</b><br>Eine schwimmende Landmarke soll sowohl Blickfang und Imagetr&auml;ger als auch sichtbares Zeichen f&uuml;r den Strukturwandel werden. Der Standort markiert gleichzeitig die Mitte des Cottbuser Ostsees. Zur Ideenfindung wurde ein studentischer Wettbewerb an der BTU Cottbus&ndash;Senftenberg durchgef&uuml;hrt. Die besten Entwurfsideen werden durch die Stadtverwaltung Cottbus&sol;Ch&oacute;&sacute;ebuz und das Ostseemanagement in die weiteren Planungen zum Cottbuser Ostsee aufgenommen und die Realisierung gepr&uuml;ft.");
//21
L.marker([51.76595, 14.40668], {icon: redIcon}).addTo(map).bindPopup("<b>21 Sport&ndash;Dreieck Cottbuser Ostsee &vert; Sportowy t&sacute;iro&zcaron;k Ch&oacute;&sacute;ebuski p&oacute;dzajt&scaron;ny jazor</b><br>Im Rahmen der Realisierung des Strukturentwicklungsprojektes &bdquo;BMX&ndash;Event&ndash; und Trainingszentrums im Sport&ndash; und Freizeitpark Cottbuser Ostsee&ldquo; sollen im s&uuml;dlichen Bereich des Cottbuser Ostsees auf H&ouml;he des Ortsteils Dissenchen neue Sport&ndash; und Freizeitnutzungen etabliert werden und den neu geschaffenen landschaftlich gepr&auml;gten Stadtraum am Wasser erlebbar machen. Ein Outdoor&ndash;Park mit landseitigen Sportangeboten sowie kleineren baulichen Anlagen (WC, Verwaltung, Caf&eacute;) als untergeordnete Nutzung ist denkbar. F&uuml;r den Spitzen&ndash;, Freizeit&ndash;, Breiten&ndash; und Vereinssport st&uuml;nden mit dem &bdquo;Sport&ndash;Dreieck&ldquo; aus Stadthafen, BMX&ndash;Zentrum&sol;Sport&ndash; und Freizeitpark sowie dem Outdoor&ndash;Sportpark vielf&auml;ltige Angebote zur Verf&uuml;gung.");
//22
L.marker([51.75496, 14.39642], {icon: redIcon}).addTo(map).bindPopup("<b>22 BUGA 2033 &ndash; Vision &vert; BUGA 2033 &ndash; wizija</b><br>In Cottbus&sol;Ch&oacute;&sacute;ebuz fand viereinhalb Jahre nach der deutschen Wiedervereinigung die erste Bundesgartenschau in den Neuen Bundesl&auml;ndern statt. Fast vier Jahrzehnte sp&auml;ter will Cottbus&sol;Ch&oacute;&sacute;ebuz wieder Gastgeber sein und den Besuchern aus Deutschland und Europa die nachhaltige Entwicklung des Zentrums der ehemaligen Tagebauregion pr&auml;sentieren. Ein BUGA-Konzept, welches die wechselvolle Geschichte von Stadt und Region erz&auml;hlt, gab es noch nie: Zwischen Innenstadt, dem Branitzer Park und dem Cottbuser Ostsee sollen vielf&auml;ltige Erlebnisr&auml;ume und Wanderpfade die Kulturgeschichte im Beziehungsgeflecht zwischen Natur, Technik, Wirtschaft, Gesellschaft, Kohleabbau, Energiegewinnung, Landschaftszerst&ouml;rung und Verlust nat&uuml;rlicher Lebensgrundlagen sowie der eigenen Identit&auml;tssuche der Menschen erlebbar machen.");
